"""add job url

Revision ID: 56efd8a7a451
Revises: 011cbf1eb761
Create Date: 2026-09-01 15:59:09.425201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56efd8a7a451'
down_revision: Union[str, Sequence[str], None] = '011cbf1eb761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_url')
    # ### end Alembic commands ###
